#cloud-config

users:  
  - name: core
    ssh-authorized-keys: 
      - ssh-rsa {ssh-rsa AAAAB3NzaC1yc2EAAAABIwAABAEAz0lX6YynZIRSOc4mLisSVhr9IpaRCzeZaBfHtXs3NoUSfShMaQULUyv/4up0BeKkmSyc+jgfx7it2TOdjolTmF1reomIGeeMrhKwjk1zSFow9naYUYWl+lBHPDsFJ0LjZ55BdiCv4NioQu0MxF+7AYdbpSptbEv8fHa1AkM4MlTrYvczdJuBsEcJGLChEnETk3nnvacIfhNPO2DqZ02bWF1o1j9qfRf/YMRgtO2Oq0CMH3KyIOiOh9yuiBT6BPJXTqmcGloIdqE8eQWE0S08BwJLxqiR+zY7ihUhaEryajRUBvx2cHHm81zjTL0J4opElAk+W3pBJZ1NJhU+OjG7+7e5fptyUjYQy0W+L4LojRoTipKs35YLSYSU/MNOdWF6pNGm1qwsbJNXG19KjdKM/wWRVsgiBVlgw8kUjJjcSeRArHCMolMRpZDwhmdeGfC3W/MyCJ6SRCCJkeOb5c3GRfudtRRC2NVCHoZXIr/0hm/2QTQo8n9UQsZILDLMI3aIAum0J6k1vYOfaOQulllKjNC28VnODx6+W3UxcDuWOYJs86y1A8mQuWQNb1bLjpIoRLM5FVO3A0EFsmqaexlZeCJuZvDVCg+O+7yJMsmYkDQsJrDh4X7vn/iahmBkkWwehFQkxlJYbTN8OZryVgFtiGR8nUPvYnzKVfMvJNV2ehHrz9r68qOcwLqalYDeK3MSfM6pQwVh36CziIxvCewsuJ3F49Mqh62Z/DHrKyUau92jrMO0KDN1eAc+jgPtpFJLc8xloYxJMEh+tKXz+P0hW7Q643IGtJROfbfdfYhdcbOcazilQVOOrR55MXJE44x0YSHxTuyCWkP3NB1Ie4LSHDlQR4cFiqiwJk/ANIxpvaH9VxvNXDmjfOPab+PQm5mLqkFZZ5wDfdYu/KmTFt/5XWpxqh2hSJUS42MeC0GqaU4y2+8vqZ9U4C4G25+YPa6LWKFhOGxPFhV8zHbPW5olG4Q2cJySxCY3dO3fVFo1oW3I+4nc8Yf/i6Wqt3mzJO3anppLMP/tQmrFfZliyf1Q4jurDDWrLoCx5b}

  - groups:
      - sudo
      - docker
